### ISSUE TITLE
คุณากร ควรให้ผลลัพธ์เป็น คุณคุณากร

### ISSUE THREAD

**Issue by surrealist** [greatfriends/khun#1]
As suggested by Khun Phakawan W. 

ผมได้เพิ่ม test case เข้าไปก่อนแล้ว แต่ยังไม่ได้โค้ดเพื่อ fix มัน (Commit 18716b1)
#### การ run test

```
C:\...\src\khun.Facts> dotnet test
```

**Comment by dinobenz** [comment]
https://github.com/greatfriends/khun/pull/2

**Comment by surrealist** [comment]
ผมทำการค้นคว้าสักหน่อยว่าคนที่ชื่อขึ้นต้นด้วย คุณ แล้วตัวที่ 4 ไม่เป็นสระมีน้อยอย่างที่คิดไหม
ปรากฏว่าเยอะครับ หยิบมา 30 ชื่อ ดูแล้วมีประมาณครึ่งหนึ่งเลย 

แต่ถึงกระนั้น ถ้าเราใช้หลัก "สระ" ก็เรียกว่าจัดการได้ไปเกินครึ่ง (แต่ต้องมีสระให้ครบถ้วนด้วย)
ส่วนชื่อ "พิเศษ" เหล่านั้น ผมเห็นว่าเราอาจจะอาศัยการเตรียมชื่อ **FirstNameThatStartsWithKhun**
เท่าที่ค้นคว้าได้เก็บไว้แบบ **hard code** เอาก็ได้ 
แล้วมาเพิ่มเติมในภายหลังเป็นระยะๆ เมื่อมีการพบหรือแจ้งเข้ามา

ปัญหาที่ควรคิดต่อไปคือ บางชื่อเราตัดสินใจชัดเจนลงไปไม่ได้ว่า
ชื่อนั้นเติมคำว่าคุณ หรือมีคำว่าคุณในชื่อจริงๆ เช่น 
"คุณภัทร" อาจจะชื่อ ภัทร ก็ได้ หรือ ชื่อ คุณภัทร ก็ได้
"คุณนิธิ" อาจจะชื่อ นิธิ หรือ คุณนิธิ ก็ได้
"คุณชนะอนันต์" อาจจะชื่อ ชนะอนันต์ หรือ คุณชนะอนันต์ ก็ได้
กรณีนี้มัน 50%/50% คือมันอาจจะถูกหรือผิดพอๆ กัน ผมเห็นว่าควรเก็บชื่อเหล่านี้
ไว้ใน list ด้วย (แยกต่างหาก) แล้วให้ถือว่า ชื่อจริงเป็นแบบสั้นๆ (เช่น นิธิ หรือ ภัทร)
โดยไม่เติม "คุณ" เพิ่มเข้าไปอีก จะ play safe กว่า

![image](https://cloud.githubusercontent.com/assets/344784/19444017/fb5a9ab6-94b8-11e6-8fc6-e0f4379ce066.png)
https://gist.github.com/surrealist/24427225d494919e99023e8bf780900c
[ที่มาของชื่อ](http://w.thaiid.org/search?Page=p1&Search=คุณ%2A)

**Comment by dinobenz** [comment]
ยากที่จะทำให้ถูกต้อง 100% เพราะบางคนชื่อขึ้นต้นด้วยคุณจริงๆ ตามตัวอย่าง
